-- luacheck config: the WoW: Forever API names this addon uses (from https://github.com/Thunderz96/forever-addon-kit data/forever_api.json, client 1.60.1 build 69893).
-- Generated by the author's tooling; regenerate it rather than edit it.
std = "lua51"
max_line_length = 120
max_string_line_length = false
codes = true
exclude_files = { "**/Libs/**", "**/libs/**" }
ignore = {
    "212", -- unused arguments: event handlers and callbacks take fixed signatures
}
read_globals = {
    "ACCEPT",
    "BreakUpLargeNumbers",
    "CANCEL",
    "CLOSE",
    "C_EncodingUtil",
    "C_Timer",
    "ChatFontSmall",
    "ClearFocus",
    "CopyTable",
    "CreateFrame",
    "CreateFromMixins",
    "CreateSettingsButtonInitializer",
    "CreateSettingsListSectionHeaderInitializer",
    "Enum",
    "GameFontHighlightSmall",
    "GameFontNormal",
    "GameFontNormalLarge",
    "GameFontNormalSmall",
    "GetCursorPosition",
    "GetRealmName",
    "GetText",
    "GetTime",
    "InCombatLockdown",
    "IsShiftKeyDown",
    "Minimap",
    "NO",
    "NumberFontNormalHuge",
    "SetCursorPosition",
    "Settings",
    "SettingsPanel",
    "StaticPopup_Show",
    "UIParent",
    "UnitName",
    "YES",
    "abs",
    "floor",
    "format",
    "gsub",
    "ipairs",
    "issecretvalue",
    "max",
    "min",
    "pairs",
    "pcall",
    "print",
    "random",
    "select",
    "sort",
    "strtrim",
    "tonumber",
    "tostring",
    "type",
    "wipe",
}
globals = { "SlashCmdList", "StaticPopupDialogs", "UISpecialFrames" }
